spring:
  application:
    name: "product-management-service"
  datasource:
    url: "jdbc:postgresql://localhost:5432/wilmastore"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
server:
  port: 8082